-- V2__create_domain_tables.sql
-- Creación de tablas de dominio para Sistema D - Matrícula académica

-- 1. Tabla base de usuarios (herencia JOINED)
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMP NOT NULL
);

-- 2. Subtabla de estudiantes
CREATE TABLE estudiantes (
    id BIGINT PRIMARY KEY,
    codigo_estudiante VARCHAR(50) NOT NULL UNIQUE,
    matricula_activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_estudiante_usuario FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 3. Subtabla de administradores
CREATE TABLE administradores (
    id BIGINT PRIMARY KEY,
    departamento VARCHAR(100) NOT NULL,
    cargo VARCHAR(100),
    CONSTRAINT fk_admin_usuario FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 4. Cursos
CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    creditos INT NOT NULL,
    porcentaje_minimo_aprobacion DOUBLE PRECISION NOT NULL DEFAULT 60.0
);

-- 5. Prerrequisitos
CREATE TABLE prerrequisitos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
    curso_principal_id BIGINT NOT NULL,
    curso_requerido_id BIGINT,
    CONSTRAINT fk_prerreq_curso_principal FOREIGN KEY (curso_principal_id) REFERENCES cursos(id) ON DELETE CASCADE,
    CONSTRAINT fk_prerreq_curso_requerido FOREIGN KEY (curso_requerido_id) REFERENCES cursos(id) ON DELETE RESTRICT
);

-- 6. Grupos
CREATE TABLE grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_grupo INT NOT NULL,
    cupo_maximo INT NOT NULL DEFAULT 30,
    curso_id BIGINT NOT NULL,
    CONSTRAINT fk_grupo_curso FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE,
    CONSTRAINT uq_grupo_curso UNIQUE (curso_id, numero_grupo)
);

-- 7. Horarios
CREATE TABLE horarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana VARCHAR(15) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    grupo_id BIGINT NOT NULL,
    CONSTRAINT fk_horario_grupo FOREIGN KEY (grupo_id) REFERENCES grupos(id) ON DELETE CASCADE
);

-- 8. Inscripciones
CREATE TABLE inscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_solicitud TIMESTAMP NOT NULL,
    estado VARCHAR(25) NOT NULL,
    posicion_lista_espera INT,
    motivo_rechazo VARCHAR(500),
    estudiante_id BIGINT NOT NULL,
    grupo_id BIGINT NOT NULL,
    CONSTRAINT fk_inscripcion_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
    CONSTRAINT fk_inscripcion_grupo FOREIGN KEY (grupo_id) REFERENCES grupos(id) ON DELETE CASCADE
);

-- 9. Historial Académico
CREATE TABLE historial_academico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    nota_final DOUBLE PRECISION,
    porcentaje_obtenido DOUBLE PRECISION,
    aprobado BOOLEAN NOT NULL,
    fecha_aprobacion DATE,
    CONSTRAINT fk_historial_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
    CONSTRAINT fk_historial_curso FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE RESTRICT
);

-- 10. Notificaciones
CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL,
    inscripcion_id BIGINT,
    mensaje VARCHAR(500) NOT NULL,
    tipo VARCHAR(35) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_notificacion_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
    CONSTRAINT fk_notificacion_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES inscripciones(id) ON DELETE SET NULL
);
